var textos_ES = {
	// header / menu
	text_titulo_app: "Aplicación ET2",
	text_titulo_menu: "Menú",
	menu_articulo: "Artículos",
	menu_ubicacion: "Ubicaciones",
	menu_alumnograduacion: "Alumnos Graduación",
	label_seleccioncolumnas: "Seleccionar columnas",

	// additional UI pieces
	text_section_article: "Sección article",
	text_footer: "Pie de página",

	// page title per-entity (added dynamically as class: text_titulo_page_<entity>)
	text_titulo_page_articulo: "Gestión de Artículos",
	text_titulo_page_alumnograduacion: "Gestión de Alumnos",
	text_titulo_page_ubicacion: "Gestión de Ubicaciones",

	// form titles per-entity/action
	text_contenido_titulo_form_articulo_ADD: "Añadir Artículo",
	text_contenido_titulo_form_articulo_EDIT: "Editar Artículo",
	text_contenido_titulo_form_articulo_DELETE: "Eliminar Artículo",
	text_contenido_titulo_form_articulo_SHOWCURRENT: "Mostrar Artículo",
	text_contenido_titulo_form_articulo_SEARCH: "Buscar Artículo",

	text_contenido_titulo_form_alumnograduacion_ADD: "Añadir Alumno",
	text_contenido_titulo_form_alumnograduacion_EDIT: "Editar Alumno",
	text_contenido_titulo_form_alumnograduacion_DELETE: "Eliminar Alumno",
	text_contenido_titulo_form_alumnograduacion_SHOWCURRENT: "Mostrar Alumno",
	text_contenido_titulo_form_alumnograduacion_SEARCH: "Buscar Alumno",

	text_contenido_titulo_form_ubicacion_ADD: "Añadir Ubicación",
	text_contenido_titulo_form_ubicacion_EDIT: "Editar Ubicación",
	text_contenido_titulo_form_ubicacion_DELETE: "Eliminar Ubicación",
	text_contenido_titulo_form_ubicacion_SHOWCURRENT: "Mostrar Ubicación",
	text_contenido_titulo_form_ubicacion_SEARCH: "Buscar Ubicación",

	// articulo labels (many are created with class="label_<FIELD>")
	label_CodigoA: "Código",
	// plain attribute names used as table header / selectable columns
	CodigoA: "Código",
	label_AutoresA: "Autores",
	AutoresA: "Autores",
	label_TituloA: "Título del artículo",
	TituloA: "Título del artículo",
	label_TituloR: "Título de la revista",
	TituloR: "Título de la revista",
	label_ISSN: "ISSN",
	ISSN: "ISSN",
	label_VolumenR: "Volumen",
	VolumenR: "Volumen",
	label_PagIniA: "Página inicio",
	PagIniA: "Página inicio",
	label_PagFinA: "Página fin",
	PagFinA: "Página fin",
	label_FechaPublicacionR: "Fecha de publicación",
	FechaPublicacionR: "Fecha de publicación",
	label_EstadoA: "Estado",
	EstadoA: "Estado",
	label_FicheropdfA: "Fichero PDF (nombre)",
	FicheropdfA: "Fichero PDF (nombre)",
	label_nuevo_FicheropdfA: "Nuevo fichero PDF",
	nuevo_FicheropdfA: "Nuevo fichero PDF",

	// alumnograduacion (labels use for=id so keys are the ids)
	alumnograduacion_login: "Login",
	alumnograduacion_password: "Contraseña",
	alumnograduacion_nombre: "Nombre",
	alumnograduacion_apellidos: "Apellidos",
	alumnograduacion_titulacion: "Titulación",
	alumnograduacion_dni: "DNI/NIE",
	alumnograduacion_telefono: "Teléfono",
	alumnograduacion_direccion: "Dirección",
	alumnograduacion_email: "Email",
	alumnograduacion_fotoacto: "Foto acto (nombre)",
	nuevo_alumnograduacion_fotoacto: "Nueva foto acto (archivo)",

	// ubicacion (keys = ids)
	id_site: "ID",
	id_site: "ID",
	site_latitud: "Latitud",
	site_latitud: "Latitud",
	site_longitud: "Longitud",
	site_longitud: "Longitud",
	site_altitude: "Altitud",
	site_altitude: "Altitud",
	site_locality: "Localidad",
	site_locality: "Localidad",
	site_provider_login: "Proveedor",
	site_provider_login: "Proveedor",
	site_north_photo: "Foto Norte (nombre)",
	nuevo_site_north_photo: "Nueva foto Norte (archivo)",
	site_south_photo: "Foto Sur (nombre)",
	nuevo_site_south_photo: "Nueva foto Sur (archivo)",
	site_east_photo: "Foto Este (nombre)",
	nuevo_site_east_photo: "Nueva foto Este (archivo)",
	site_west_photo: "Foto Oeste (nombre)",
	nuevo_site_west_photo: "Nueva foto Oeste (archivo)",

	// generic UI elements
	submit_button: "Enviar",
	BACK: "Volver",
	// table/action headers
	EDIT: "Editar",
	DELETE: "Eliminar",
	SHOWCURRENT: "Mostrar",
	ADD: "Añadir",
	SEARCH: "Buscar",
	RECORDSET_VACIO: "No se han encontrado elementos que coincidan con la búsqueda",

	// a small set of common validation messages (expand as needed)
	CodigoA_format_KO: "Código: formato inválido (solo dígitos)",
	CodigoA_min_size_KO: "Código: valor numérico inválido",
	AutoresA_min_size_KO: "Autores: longitud mínima no alcanzada",
	TituloA_min_size_KO: "Título: longitud mínima no alcanzada",
	FechaPublicacionR_format_KO: "Fecha: formato inválido (usa DD/MM/YYYY, o deja vacío para usar valor por defecto)",
	FechaPublicacionR_future_KO: "Fecha: no puede ser futura",
	nuevo_FicheropdfA_type_file_KO: "El fichero debe ser PDF",

	alumnograduacion_dni_format_KO: "DNI/NIE: formato inválido",
	alumnograduacion_login_min_size_KO: "Login: longitud mínima no alcanzada",

	id_site_format_KO: "ID: solo dígitos permitidos",
	site_latitud_format_KO: "Latitud: formato inválido (ej. 41.385063)",
	site_longitud_format_KO: "Longitud: formato inválido (ej. -3.703790)",
	site_locality_min_size_KO: "Localidad: longitud mínima no alcanzada",

	// additional validation keys discovered in rules/tests
	CodigoA_max_size_KO: "Código: excede tamaño máximo (11 dígitos)",
	AutoresA_max_size_KO: "Autores: longitud máxima superada",
	AutoresA_format_KO: "Autores: formato inválido (solo letras y espacios)",
	TituloA_max_size_KO: "Título: longitud máxima superada",
	TituloA_format_KO: "Título: formato inválido",
	TituloR_min_size_KO: "Título revista: longitud mínima no alcanzada",
	TituloR_max_size_KO: "Título revista: longitud máxima superada",
	TituloR_format_KO: "Título revista: formato inválido",
	ISSN_min_size_KO: "ISSN: longitud inválida (9 caracteres)",
	ISSN_max_size_KO: "ISSN: longitud inválida (9 caracteres)",
	ISSN_format_KO: "ISSN: formato inválido (####-####)",
	VolumenR_min_size_KO: "Volumen: longitud mínima no alcanzada",
	VolumenR_max_size_KO: "Volumen: longitud máxima superada",
	VolumenR_format_KO: "Volumen: debe ser numérico",
	PagIniA_min_size_KO: "Página inicio: longitud mínima no alcanzada",
	PagIniA_max_size_KO: "Página inicio: longitud máxima superada",
	PagIniA_format_KO: "Página inicio: formato inválido (número)",
	PagFinA_min_size_KO: "Página fin: longitud mínima no alcanzada",
	PagFinA_max_size_KO: "Página fin: longitud máxima superada",
	PagFinA_format_KO: "Página fin: formato inválido (número)",
	PagFinA_logic_KO: "Página fin: debe ser mayor o igual que página inicio",
	FechaPublicacionR_max_size_KO: "Fecha: demasiados caracteres",
	EstadoA_valor_KO: "Estado: valor inválido",
	EstadoA_max_size_KO: "Estado: longitud máxima superada",
	FicheropdfA_max_size_name_file_KO: "Nombre de fichero: supera longitud máxima (20)",
	FicheropdfA_format_name_file_KO: "Nombre de fichero: formato inválido",
	nuevo_FicheropdfA_not_exist_file_KO: "Debe subir un fichero PDF",
	nuevo_FicheropdfA_max_size_file_KO: "Fichero demasiado grande (máx 2MB)",
	nuevo_FicheropdfA_name_min_size_file_KO: "Nombre de fichero: demasiado corto",
	nuevo_FicheropdfA_name_max_size_file_KO: "Nombre de fichero: demasiado largo",
	nuevo_FicheropdfA_format_name_file_KO: "Nombre de fichero: formato inválido",

	// alumnograduacion extras
	alumnograduacion_dni_min_size_KO: "DNI/NIE: longitud mínima no alcanzada",
	alumnograduacion_dni_max_size_KO: "DNI/NIE: longitud máxima no alcanzada",
	alumnograduacion_login_max_size_KO: "Login: longitud máxima superada",
	alumnograduacion_login_format_KO: "Login: formato inválido",
	alumnograduacion_titulacion_invalid_KO: "Titulación: valor inválido",
	alumnograduacion_password_min_size_KO: "Contraseña: longitud mínima no alcanzada",
	alumnograduacion_password_max_size_KO: "Contraseña: longitud máxima superada",
	alumnograduacion_password_format_KO: "Contraseña: formato inválido",
	alumnograduacion_telefono_min_size_KO: "Teléfono: longitud mínima no alcanzada",
	alumnograduacion_telefono_max_size_KO: "Teléfono: longitud máxima superada",
	alumnograduacion_telefono_format_KO: "Teléfono: formato inválido (9 dígitos)",
	alumnograduacion_nombre_min_size_KO: "Nombre: longitud mínima no alcanzada",
	alumnograduacion_nombre_max_size_KO: "Nombre: longitud máxima superada",
	alumnograduacion_nombre_format_KO: "Nombre: formato inválido",
	alumnograduacion_apellidos_min_size_KO: "Apellidos: longitud mínima no alcanzada",
	alumnograduacion_apellidos_max_size_KO: "Apellidos: longitud máxima superada",
	alumnograduacion_apellidos_format_KO: "Apellidos: formato inválido",
	alumnograduacion_direccion_min_size_KO: "Dirección: longitud mínima no alcanzada",
	alumnograduacion_direccion_max_size_KO: "Dirección: longitud máxima superada",
	alumnograduacion_direccion_format_KO: "Dirección: formato inválido",
	alumnograduacion_email_min_size_KO: "Email: longitud mínima no alcanzada",
	alumnograduacion_email_max_size_KO: "Email: longitud máxima superada",
	alumnograduacion_email_format_KO: "Email: formato inválido",
	nuevo_alumnograduacion_fotoacto_not_exist_file_KO: "La imagen no existe",
	nuevo_alumnograduacion_fotoacto_format_name_file_KO: "Nombre de imagen: formato inválido",
	nuevo_alumnograduacion_fotoacto_max_size_file_KO: "Imagen demasiado grande",
	nuevo_alumnograduacion_fotoacto_name_min_size_file_KO: "Nombre de imagen: demasiado corto",
	nuevo_alumnograduacion_fotoacto_name_max_size_file_KO: "Nombre de imagen: demasiado largo",

	// ubicacion extras
	site_altitude_format_KO: "Altitud: formato inválido (número)",
	site_locality_max_size_KO: "Localidad: longitud máxima superada",
	site_provider_login_min_size_KO: "Proveedor: longitud mínima no alcanzada",
	site_provider_login_max_size_KO: "Proveedor: longitud máxima superada",
	nuevo_site_north_photo_not_exist_file_KO: "Fichero no existe",
	nuevo_site_north_photo_format_name_file_KO: "Nombre de fichero: formato inválido",
	nuevo_site_north_photo_max_size_file_KO: "Fichero demasiado grande",
	nuevo_site_south_photo_not_exist_file_KO: "Fichero no existe",
	// Traducciones para Sur, Este, Oeste (formato/tamaño/no existe) — igual que Norte
	nuevo_site_south_photo_format_name_file_KO: "Nombre de fichero: formato inválido",
	nuevo_site_south_photo_max_size_file_KO: "Fichero demasiado grande",
	nuevo_site_east_photo_not_exist_file_KO: "Fichero no existe",
	nuevo_site_east_photo_format_name_file_KO: "Nombre de fichero: formato inválido",
	nuevo_site_east_photo_max_size_file_KO: "Fichero demasiado grande",
	nuevo_site_west_photo_not_exist_file_KO: "Fichero no existe",
	nuevo_site_west_photo_format_name_file_KO: "Nombre de fichero: formato inválido",
	nuevo_site_west_photo_max_size_file_KO: "Fichero demasiado grande",
	site_north_photo_max_size_KO: "Nombre de fichero demasiado largo",
	site_north_photo_format_KO: "Formato de nombre inválido",
	site_south_photo_max_size_KO: "Nombre de fichero demasiado largo",
	site_south_photo_format_KO: "Formato de nombre inválido",
	site_east_photo_max_size_KO: "Nombre de fichero demasiado largo",
	site_east_photo_format_KO: "Formato de nombre inválido",
	site_west_photo_max_size_KO: "Nombre de fichero demasiado largo",
	site_west_photo_format_KO: "Formato de nombre inválido",

	// added translations for newly-introduced validation keys
	id_site_min_size_KO: "ID fuera de rango (demasiado pequeño)",
	id_site_max_size_KO: "ID fuera de rango (demasiado grande)",
	site_latitud_min_size_KO: "Latitud fuera de rango (demasiado baja)",
	site_latitud_max_size_KO: "Latitud fuera de rango (demasiado alta)",
	site_longitud_min_size_KO: "Longitud fuera de rango (demasiado baja)",
	site_longitud_max_size_KO: "Longitud fuera de rango (demasiado alta)",
	site_altitude_min_size_KO: "Altitud fuera de rango (demasiado baja)",
	site_altitude_max_size_KO: "Altitud fuera de rango (demasiado alta)",

	site_north_photo_min_size_KO: "Nombre de fichero demasiado corto",
	site_south_photo_min_size_KO: "Nombre de fichero demasiado corto",
	site_east_photo_min_size_KO: "Nombre de fichero demasiado corto",
	site_west_photo_min_size_KO: "Nombre de fichero demasiado corto",

	nuevo_site_north_photo_name_min_size_file_KO: "Nombre de fichero: demasiado corto",
	nuevo_site_north_photo_max_name_size_file_KO: "Nombre de fichero: demasiado largo",
	nuevo_site_south_photo_name_min_size_file_KO: "Nombre de fichero: demasiado corto",
	nuevo_site_south_photo_max_name_size_file_KO: "Nombre de fichero: demasiado largo",
	nuevo_site_east_photo_name_min_size_file_KO: "Nombre de fichero: demasiado corto",
	nuevo_site_east_photo_max_name_size_file_KO: "Nombre de fichero: demasiado largo",
	nuevo_site_west_photo_name_min_size_file_KO: "Nombre de fichero: demasiado corto",
	nuevo_site_west_photo_max_name_size_file_KO: "Nombre de fichero: demasiado largo",

	// Validación de tipo JPEG (aplicada a todos los uploads de fotos)
	nuevo_alumnograduacion_fotoacto_type_file_jpeg_KO: "Solo se permiten archivos JPEG/JPG",
	nuevo_FicheropdfA_type_file_jpeg_KO: "Solo se permiten archivos JPEG/JPG",
	nuevo_site_north_photo_type_file_jpeg_KO: "Solo se permiten archivos JPEG/JPG",
	nuevo_site_south_photo_type_file_jpeg_KO: "Solo se permiten archivos JPEG/JPG",
	nuevo_site_east_photo_type_file_jpeg_KO: "Solo se permiten archivos JPEG/JPG",
	nuevo_site_west_photo_type_file_jpeg_KO: "Solo se permiten archivos JPEG/JPG",

	// Generic Validation Errors
	ERROR_MIN_SIZE: "El tamaño debe ser mayor que ####",
	ERROR_MAX_SIZE: "El tamaño debe ser menor que ####",
	ERROR_EXP_REG: "El formato no es correcto (####)",
	ERROR_NO_FILE: "Es obligatorio subir un archivo",
	ERROR_TYPE_FILE: "El tipo de archivo no es válido",
	ERROR_DATE_FORMAT: "La fecha debe tener el formato DD/MM/YYYY",

	// action modal errors (examples)
	ACTION_ERROR_GENERIC: "Se ha producido un error en la acción",
	ACTION_SUCCESS: "Acción realizada con éxito",
};
