var textos_EN = {
	// header / menu
	text_titulo_app: "ET2 Application",
	text_titulo_menu: "Menu",
	menu_articulo: "Articles",
	menu_ubicacion: "Locations",
	menu_alumnograduacion: "Graduation Students",
	label_seleccioncolumnas: "Select columns",

	// additional UI pieces
	text_section_article: "Article section",
	text_footer: "Footer",

	// page title per-entity
	text_titulo_page_articulo: "Article Management",
	text_titulo_page_alumnograduacion: "Student Management",
	text_titulo_page_ubicacion: "Location Management",

	// form titles per-entity/action
	text_contenido_titulo_form_articulo_ADD: "Add Article",
	text_contenido_titulo_form_articulo_EDIT: "Edit Article",
	text_contenido_titulo_form_articulo_DELETE: "Delete Article",
	text_contenido_titulo_form_articulo_SHOWCURRENT: "Show Article",
	text_contenido_titulo_form_articulo_SEARCH: "Search Article",

	text_contenido_titulo_form_alumnograduacion_ADD: "Add Student",
	text_contenido_titulo_form_alumnograduacion_EDIT: "Edit Student",
	text_contenido_titulo_form_alumnograduacion_DELETE: "Delete Student",
	text_contenido_titulo_form_alumnograduacion_SHOWCURRENT: "Show Student",
	text_contenido_titulo_form_alumnograduacion_SEARCH: "Search Student",

	text_contenido_titulo_form_ubicacion_ADD: "Add Location",
	text_contenido_titulo_form_ubicacion_EDIT: "Edit Location",
	text_contenido_titulo_form_ubicacion_DELETE: "Delete Location",
	text_contenido_titulo_form_ubicacion_SHOWCURRENT: "Show Location",
	text_contenido_titulo_form_ubicacion_SEARCH: "Search Location",

	// articulo labels
	label_CodigoA: "Code",
	// plain attribute names used as table header / selectable columns
	CodigoA: "Code",
	label_AutoresA: "Authors",
	AutoresA: "Authors",
	label_TituloA: "Article title",
	TituloA: "Article title",
	label_TituloR: "Journal title",
	TituloR: "Journal title",
	label_ISSN: "ISSN",
	ISSN: "ISSN",
	label_VolumenR: "Volume",
	VolumenR: "Volume",
	label_PagIniA: "Page start",
	PagIniA: "Page start",
	label_PagFinA: "Page end",
	PagFinA: "Page end",
	label_FechaPublicacionR: "Publication date",
	FechaPublicacionR: "Publication date",
	label_EstadoA: "State",
	EstadoA: "State",
	label_FicheropdfA: "PDF file (name)",
	FicheropdfA: "PDF file (name)",
	label_nuevo_FicheropdfA: "New PDF file",
	nuevo_FicheropdfA: "New PDF file",

	// alumnograduacion
	alumnograduacion_login: "Login",
	alumnograduacion_password: "Password",
	alumnograduacion_nombre: "Name",
	alumnograduacion_apellidos: "Last name",
	alumnograduacion_titulacion: "Degree",
	alumnograduacion_dni: "DNI/NIE",
	alumnograduacion_telefono: "Phone",
	alumnograduacion_direccion: "Address",
	alumnograduacion_email: "Email",
	alumnograduacion_fotoacto: "Event photo (name)",
	nuevo_alumnograduacion_fotoacto: "New event photo (file)",

	// ubicacion
	id_site: "ID",
	id_site: "ID",
	site_latitud: "Latitude",
	site_latitud: "Latitude",
	site_longitud: "Longitude",
	site_longitud: "Longitude",
	site_altitude: "Altitude",
	site_altitude: "Altitude",
	site_locality: "Locality",
	site_locality: "Locality",
	site_provider_login: "Provider",
	site_provider_login: "Provider",
	site_north_photo: "North photo (name)",
	nuevo_site_north_photo: "New north photo (file)",
	site_south_photo: "South photo (name)",
	nuevo_site_south_photo: "New south photo (file)",
	site_east_photo: "East photo (name)",
	nuevo_site_east_photo: "New east photo (file)",
	site_west_photo: "West photo (name)",
	nuevo_site_west_photo: "New west photo (file)",

	// generic UI
	submit_button: "Submit",
	BACK: "Back",
	// table/action headers
	EDIT: "Edit",
	DELETE: "Delete",
	SHOWCURRENT: "Show",
	ADD: "Add",
	SEARCH: "Search",
	RECORDSET_VACIO: "No items matched the search",

	// small set of validation messages (expand as needed)
	CodigoA_format_KO: "Code: invalid format (digits only)",
	CodigoA_min_size_KO: "Code: invalid numeric value",
	AutoresA_min_size_KO: "Authors: minimum length not met",
	TituloA_min_size_KO: "Title: minimum length not met",
	FechaPublicacionR_format_KO: "Date: invalid format (use DD/MM/YYYY, or leave empty for default)",
	FechaPublicacionR_future_KO: "Date: can't be in the future",
	nuevo_FicheropdfA_type_file_KO: "File must be PDF",

	alumnograduacion_dni_format_KO: "DNI/NIE: invalid format",
	alumnograduacion_login_min_size_KO: "Login: minimum length not met",

	id_site_format_KO: "ID: digits only allowed",
	site_latitud_format_KO: "Latitude: invalid format (eg. 41.385063)",
	site_longitud_format_KO: "Longitude: invalid format (eg. -3.703790)",
	site_locality_min_size_KO: "Locality: minimum length not met",

	// additional validation keys discovered in rules/tests
	CodigoA_max_size_KO: "Code: exceeds maximum size (11 digits)",
	AutoresA_max_size_KO: "Authors: exceeds maximum length",
	AutoresA_format_KO: "Authors: invalid format (letters and spaces only)",
	TituloA_max_size_KO: "Title: exceeds maximum length",
	TituloA_format_KO: "Title: invalid format",
	TituloR_min_size_KO: "Journal title: minimum length not met",
	TituloR_max_size_KO: "Journal title: exceeds maximum length",
	TituloR_format_KO: "Journal title: invalid format",
	ISSN_min_size_KO: "ISSN: invalid length (9 chars)",
	ISSN_max_size_KO: "ISSN: invalid length (9 chars)",
	ISSN_format_KO: "ISSN: invalid format (####-####)",
	VolumenR_min_size_KO: "Volume: minimum length not met",
	VolumenR_max_size_KO: "Volume: exceeds maximum length",
	VolumenR_format_KO: "Volume: must be numeric",
	PagIniA_min_size_KO: "Page start: minimum length not met",
	PagIniA_max_size_KO: "Page start: exceeds maximum length",
	PagIniA_format_KO: "Page start: invalid format (number)",
	PagFinA_min_size_KO: "Page end: minimum length not met",
	PagFinA_max_size_KO: "Page end: exceeds maximum length",
	PagFinA_format_KO: "Page end: invalid format (number)",
	PagFinA_logic_KO: "Page end: must be greater or equal than page start",
	FechaPublicacionR_max_size_KO: "Date: too many characters",
	EstadoA_valor_KO: "State: invalid value",
	EstadoA_max_size_KO: "State: exceeds maximum length",
	FicheropdfA_max_size_name_file_KO: "Filename: exceeds maximum length (20)",
	FicheropdfA_format_name_file_KO: "Filename: invalid format",
	nuevo_FicheropdfA_not_exist_file_KO: "You must upload a PDF file",
	nuevo_FicheropdfA_max_size_file_KO: "File too large (max 2MB)",
	nuevo_FicheropdfA_name_min_size_file_KO: "Filename: too short",
	nuevo_FicheropdfA_name_max_size_file_KO: "Filename: too long",
	nuevo_FicheropdfA_format_name_file_KO: "Filename: invalid format",

	// alumnograduacion extras
	alumnograduacion_dni_min_size_KO: "DNI/NIE: minimum length not met",
	alumnograduacion_dni_max_size_KO: "DNI/NIE: maximum length exceeded",
	alumnograduacion_login_max_size_KO: "Login: exceeds maximum length",
	alumnograduacion_login_format_KO: "Login: invalid format",
	alumnograduacion_titulacion_invalid_KO: "Degree: invalid value",
	alumnograduacion_password_min_size_KO: "Password: minimum length not met",
	alumnograduacion_password_max_size_KO: "Password: exceeds maximum length",
	alumnograduacion_password_format_KO: "Password: invalid format",
	alumnograduacion_telefono_min_size_KO: "Phone: minimum length not met",
	alumnograduacion_telefono_max_size_KO: "Phone: exceeds maximum length",
	alumnograduacion_telefono_format_KO: "Phone: invalid format (9 digits)",
	alumnograduacion_nombre_min_size_KO: "Name: minimum length not met",
	alumnograduacion_nombre_max_size_KO: "Name: exceeds maximum length",
	alumnograduacion_nombre_format_KO: "Name: invalid format",
	alumnograduacion_apellidos_min_size_KO: "Last name: minimum length not met",
	alumnograduacion_apellidos_max_size_KO: "Last name: exceeds maximum length",
	alumnograduacion_apellidos_format_KO: "Last name: invalid format",
	alumnograduacion_direccion_min_size_KO: "Address: minimum length not met",
	alumnograduacion_direccion_max_size_KO: "Address: exceeds maximum length",
	alumnograduacion_direccion_format_KO: "Address: invalid format",
	alumnograduacion_email_min_size_KO: "Email: minimum length not met",
	alumnograduacion_email_max_size_KO: "Email: exceeds maximum length",
	alumnograduacion_email_format_KO: "Email: invalid format",
	nuevo_alumnograduacion_fotoacto_not_exist_file_KO: "Image does not exist",
	nuevo_alumnograduacion_fotoacto_format_name_file_KO: "Image filename: invalid format",
	nuevo_alumnograduacion_fotoacto_max_size_file_KO: "Image too large",
	nuevo_alumnograduacion_fotoacto_name_min_size_file_KO: "Image filename: too short",
	nuevo_alumnograduacion_fotoacto_name_max_size_file_KO: "Image filename: too long",

	// ubicacion extras
	site_altitude_format_KO: "Altitude: invalid format (number)",
	site_locality_max_size_KO: "Locality: exceeds maximum length",
	site_provider_login_min_size_KO: "Provider: minimum length not met",
	site_provider_login_max_size_KO: "Provider: exceeds maximum length",
	nuevo_site_north_photo_not_exist_file_KO: "File does not exist",
	nuevo_site_north_photo_format_name_file_KO: "Filename: invalid format",
	nuevo_site_north_photo_max_size_file_KO: "File too large",
	nuevo_site_south_photo_not_exist_file_KO: "File does not exist",
	// South, East, West translations (format/max-size/not-exist) — kept consistent with North
	nuevo_site_south_photo_format_name_file_KO: "Filename: invalid format",
	nuevo_site_south_photo_max_size_file_KO: "File too large",
	nuevo_site_east_photo_not_exist_file_KO: "File does not exist",
	nuevo_site_east_photo_format_name_file_KO: "Filename: invalid format",
	nuevo_site_east_photo_max_size_file_KO: "File too large",
	nuevo_site_west_photo_not_exist_file_KO: "File does not exist",
	nuevo_site_west_photo_format_name_file_KO: "Filename: invalid format",
	nuevo_site_west_photo_max_size_file_KO: "File too large",
	site_north_photo_max_size_KO: "Filename too long",
	site_north_photo_format_KO: "Filename invalid format",
	site_south_photo_max_size_KO: "Filename too long",
	site_south_photo_format_KO: "Filename invalid format",
	site_east_photo_max_size_KO: "Filename too long",
	site_east_photo_format_KO: "Filename invalid format",
	site_west_photo_max_size_KO: "Filename too long",
	site_west_photo_format_KO: "Filename invalid format",

	// added translations for newly-introduced validation keys
	id_site_min_size_KO: "ID out of range (too small)",
	id_site_max_size_KO: "ID out of range (too large)",
	site_latitud_min_size_KO: "Latitude out of range (too low)",
	site_latitud_max_size_KO: "Latitude out of range (too high)",
	site_longitud_min_size_KO: "Longitude out of range (too low)",
	site_longitud_max_size_KO: "Longitude out of range (too high)",
	site_altitude_min_size_KO: "Altitude out of range (too low)",
	site_altitude_max_size_KO: "Altitude out of range (too high)",

	site_north_photo_min_size_KO: "Filename too short",
	site_south_photo_min_size_KO: "Filename too short",
	site_east_photo_min_size_KO: "Filename too short",
	site_west_photo_min_size_KO: "Filename too short",

	nuevo_site_north_photo_name_min_size_file_KO: "Filename: too short",
	nuevo_site_north_photo_max_name_size_file_KO: "Filename: too long",
	nuevo_site_south_photo_name_min_size_file_KO: "Filename: too short",
	nuevo_site_south_photo_max_name_size_file_KO: "Filename: too long",
	nuevo_site_east_photo_name_min_size_file_KO: "Filename: too short",
	nuevo_site_east_photo_max_name_size_file_KO: "Filename: too long",
	nuevo_site_west_photo_name_min_size_file_KO: "Filename: too short",
	nuevo_site_west_photo_max_name_size_file_KO: "Filename: too long",

	// JPEG file type validation (applied to all photo uploads)
	nuevo_alumnograduacion_fotoacto_type_file_jpeg_KO: "Only JPEG/JPG files are allowed",
	nuevo_FicheropdfA_type_file_jpeg_KO: "Only JPEG/JPG files are allowed",
	nuevo_site_north_photo_type_file_jpeg_KO: "Only JPEG/JPG files are allowed",
	nuevo_site_south_photo_type_file_jpeg_KO: "Only JPEG/JPG files are allowed",
	nuevo_site_east_photo_type_file_jpeg_KO: "Only JPEG/JPG files are allowed",
	nuevo_site_west_photo_type_file_jpeg_KO: "Only JPEG/JPG files are allowed",

	// Generic Validation Errors
	ERROR_MIN_SIZE: "The size must be greater than ####",
	ERROR_MAX_SIZE: "The size must be less than ####",
	ERROR_EXP_REG: "The format is incorrect (####)",
	ERROR_NO_FILE: "File upload is mandatory",
	ERROR_TYPE_FILE: "File type is invalid",
	ERROR_DATE_FORMAT: "Date must be in DD/MM/YYYY format",

	// action modal errors
	ACTION_ERROR_GENERIC: "An error occurred during the action",
	ACTION_SUCCESS: "Action completed successfully",
};
